### ISSUE TITLE
Add subsumptions to GO terms to NBO

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#113]
Add subsumptions to GO terms to NBO so that the XPO behaviors classify correctly.

**Comment by malcolmfisher103** [comment]
I think this is related, but maybe it should be its own issue. Absent and abnormal behavioral phenotypes seem to be siblings rather than absent being a child of abnormal as it is for the anatomical structure phenotypes. I think this may apply to other GO branches as well such as Biological Process. This also affects the NBO terms leading to absent surface breathing being a direct child of 'Xenopus phenotype'.

**Comment by matentzn** [comment]
The question of absence and abnormal is a different one that has been extensively discussed by the phenotype editors and remain a big point of contention. I will propose a solution at the next call and with a bit of luck, the issue will solve itself for you in the next month. Unfortunately, this won't be fixed very quickly for any of the other ontologies that are not pattern-driven like you are :P

**Comment by matentzn** [comment]
There is generally also a philosophical problem whether an absent entity is really abnormal or not - but there is good reason in the phenotype world to make it so.
