### ISSUE TITLE
Add date field

### ISSUE THREAD

**Issue by seger** [obophenotype/xenopus-phenotype-ontology#151]
The current XPO file ( both obo and owl format ) are reported to be missing the date field in the metadata at the top of the file.
May we obtain an update to the XPO that contains the date ( essential the creation date of the ontology file ) in a similar manner as other ontologies.

The format is typically given as 

date: 03:16:2021 10:38

**Comment by matentzn** [comment]
Hey @seger, great to hear from you again!

The date field is an ancient habit of OBO file format development, and we do not really do that anymore, because we have:

VersionIRI, which has a date, 

```
data-version: releases/2021-03-05
```

and versionInfo

```
property_value: owl:versionInfo "2021-03-05" xsd:string
```

It occurs to me that having two dates is enough  - if you chose to add another one, then you will have to update the entire ODK config (as you have to inject it automatically). Is the use case a strong one?

**Comment by seger** [comment]
Hi @matentzn – This was a request from Troy at Xenbase, who loads the ontologies into the database, so I'll check with him whether he can just use what's in the ontology now. I'd rather not have to fool with updating a config needlessly.

**Comment by matentzn** [comment]
Cool, I agree :)
